### ISSUE TITLE
Not hiding overlay with HUD

### ISSUE THREAD

**Issue by CharonM72** [karashiiro/PingPlugin#12]
I have installed the Ping Plugin 1.5.0.1 via XLPlugins and whether I turn on or turn off "Hide overlays with HUD", the overlay does not hide when I press the hide HUD hotkey. Other overlays (like the FPS Overlay) do. It's quite bothersome because it also shows up in in-game screenshots.

**Comment by karashiiro** [comment]
Noted, I'll lift a fix for this from FPSPlugin when I'm back home in a few days.

**Comment by karashiiro** [comment]
Closed with v1.5.1, waiting for merge.

**Comment by CharonM72** [comment]
It looks like it is correctly hiding when I hide the HUD now but... now when I unhide the HUD, it remains hidden, it seems.

**Comment by karashiiro** [comment]
Waiting on another update merge, that bit of memory was updated this patch.

**Comment by karashiiro** [comment]
Should be available now.
