### ISSUE TITLE
Hide during cutscenes?

### ISSUE THREAD

**Issue by CharonM72** [karashiiro/PingPlugin#14]
Hello,

I noticed that the Ping Plugin stays active during things like cutscenes and loading screens etc. where other plugins like FPS plugin disappear. Is this something that could be implemented?

Thanks.

**Comment by karashiiro** [comment]
That functionality is now natively in Dalamud, everyone else has just been too lazy to remove it from their own things. You can enable the feature in `/xlsettings`, under Look & Feel.

**Comment by CharonM72** [comment]
Ah, I have that setting checked, but Ping Plugin still appears during cutscenes.

**Comment by karashiiro** [comment]
Nice, turns out I misunderstood what the native implementation actually does. I'll reimplement that.

**Comment by karashiiro** [comment]
PR closed, it's going to be added to the native implementation

**Comment by karashiiro** [comment]
Added with https://github.com/goatcorp/Dalamud/pull/165, waiting on a new release.

**Comment by karashiiro** [comment]
Fixed
