### ISSUE TITLE
Not working with Mudfish even with FastConnect disabled

### ISSUE THREAD

**Issue by 0kie** [karashiiro/PingPlugin#16]
Since the last update it isn't working for me anymore while using mudfish, I don't have FastConnect  enabled.
I tried by using mudfish's default client and also through proxifier.

After the update it only shows the ping as 0ms (which I'm aware it's what happens when FastConnect is enabled), it's also connecting to localhost (127.0.0.1)

Before the update it used to work normally while using mudfish through proxifier.

**Comment by karashiiro** [comment]
Closing after https://github.com/goatcorp/DalamudPlugins/pull/726
