### ISSUE TITLE
Possible issue with VPN

### ISSUE THREAD

**Issue by mattskiiau** [karashiiro/PingPlugin#24]
Using a VPN (EXITLAG), provides a different ping over what is seen via the plugin. 
![image](https://user-images.githubusercontent.com/20663861/145512777-17f424b7-197c-422f-bd1a-d0971ae348d0.png)
![image](https://user-images.githubusercontent.com/20663861/145512804-0535c7ee-6f61-43c3-ad6b-222bf9a7ace4.png)

**Comment by karashiiro** [comment]
Gaming VPNs make the ping tracker have slightly inaccurate readouts sometimes. I’ve gotten it to a point where it’s pretty close to the actual ping, but it’s not perfect. That said, that’s only about 10 milliseconds off, so that looks alright.

**Comment by yjywybb** [comment]
In my case, it points to 127.0.0.1. (Worked properly before EndWalker)

**Comment by mattskiiau** [comment]
In my case, Since Exitlag does not run in full tunnel mode, I'm unable to verify what the true ping is to see if either the client or the plugin is incorrect.

**Comment by karashiiro** [comment]
Should be fixed with v1.14.2, let me know if it works.
