### ISSUE TITLE
Font Scale Resizes Config Window

### ISSUE THREAD

**Issue by keoShine** [karashiiro/PingPlugin#29]
Currently, the Font Scale slider resizes the Config window as well as the Ping Monitor window.. This makes it difficult to change the size of the monitor window since the config window that the font scale slider is on keeps moving as it resizes itself.. It would be helpful if the Config window always stayed the same size, especially since it's not likely to be always open like the monitor window is..

**Comment by karashiiro** [comment]
I originally had it all tied together since I figured people would have equal difficulties reading the config window and the ping monitor, but I think enough people have brought this up now that it's clear that's not the case.

I'll change that in a minute 👍

**Comment by karashiiro** [comment]
Fixed in v1.15.0 https://github.com/goatcorp/DalamudPlugins/pull/1731
