### ISSUE TITLE
Ping does not match latency from the TCP connection of the ffxiv process

### ISSUE THREAD

**Issue by ohhopi** [karashiiro/PingPlugin#3]
To the best of my knowledge, the "realest" latency one has with the FFXIV servers is the TCP connection latency used by the FFXIV process, and it can be found in Windows in the Resource Monitor.

When checking if the ping shown in the plugin matches, I found that 90% of the time in my case, the latency is different (see attached screenshot).

![image](https://user-images.githubusercontent.com/64282231/80921411-91ccd900-8d76-11ea-999f-def43469d48d.png)

Since I have no knowledge of C# I have no idea what exactly you are "pinging" but the value shown by the plugin matches what I get when doing a ping in a terminal and not the ping from the actual connection, which to the best of my knowledge is far more useful.

I guess this issue is more of a question at the moment.

**Comment by karashiiro** [comment]
The plugin does an ICMP ping, so it will be an underestimate, currently. I am, however, looking into piping typeperf instead, which should be more reliably functional and be as accurate as resmon.

**Comment by karashiiro** [comment]
Actually, it looks like there's a WinAPI method to just get that information directly, so I'll figure out and implement that over the next few days: https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getpertcpconnectionestats?redirectedfrom=MSDN

**Comment by karashiiro** [comment]
To specifically answer your question, the ping currently shown by the plugin is the ping you would get from running the `ping` command from the console. This is the minimum latency between you and the gateway server, not the usual latency between you and the game server behind that. The two numbers are sometimes the same, but the latency between you and the game server can be higher than the value shown.

I'm working on fixing this by using a better API method.

**Comment by ohhopi** [comment]
Thanks for the quick answer(s), i'll be waiting eagerly to see the update :)
