### ISSUE TITLE
An option to attach to Server Info Hud Element

### ISSUE THREAD

**Issue by SelfAfflicted** [karashiiro/PingPlugin#30]
I've tried dozens of times to set the color and size to match this hud element, but cannot seem to do so, but I thought, if the Orchestrion plugin song titles can be attached to it seamlessly and SimpleTweaks time format manipulation than surely this one can as well  ![image](https://user-images.githubusercontent.com/13339406/146816195-a1e8ae2b-da07-4025-98b8-98eccc956c23.png)

**Comment by RainerZufahl** [comment]
i second this idea! 

ive been trying to understand exactly what methods in porch's code place it in the server info, but have failed so far. but i'd be willing to help out with the little coding experience i have if needed

**Comment by karashiiro** [comment]
Feel free to have a go at it, I've been busy handling other requests recently so I haven't had time to work on this one. Otherwise, I'll get to this eventually.

**Comment by karashiiro** [comment]
Should be implemented as of [v2.2](https://github.com/goatcorp/DalamudPlugins/pull/1982)

**Comment by SelfAfflicted** [comment]
You're amazing, looks a thousand times better than how I had it, thank you!
