### ISSUE TITLE
Not showing correct ping value.

### ISSUE THREAD

**Issue by ashr420** [karashiiro/PingPlugin#31]
the plugin hasnt worked properly for me since EW. I am using exit lag, is there any solution or fix?

**Comment by karashiiro** [comment]
I released a fix last week or so that should’ve made it not show 0ms, did that not work? Besides that, gaming VPNs screw with the plugin’s ping detection, so it won’t be exactly correct. I still don’t have a good fix for this, but it should at least show something with +/-20ms of the correct value.

**Comment by ashr420** [comment]
it never showed me 0 m/s but extremely high values such as 400ms etc. Rn on exit lag it shows im connected at 100 ms but the plugin  says i have 160ms :(

**Comment by karashiiro** [comment]
Yeah, extreme instability is pretty typical in PingPlugin with VPNs, I’ll leave this open (because it is a bug) but I really don’t have any directions for better solutions right now, at least until I stumble upon something, or until someone knowledgable can drop a hint in #28

**Comment by karashiiro** [comment]
I’ll continue messing with it anyways, but I’m mostly out of ideas at this point.

**Comment by ashr420** [comment]
Alright, hope it gets fixed in the future because i love the plugin! Thanks for the quick response :D

**Comment by karashiiro** [comment]
Released [v2.0](https://github.com/goatcorp/DalamudPlugins/pull/1953), let me know if that fixes everything.

**Comment by ashr420** [comment]
its working now, thanks!
