### ISSUE TITLE
Plugin has always showed 0ms; no VPN, but on Pop!_OS Linux.

### ISSUE THREAD

**Issue by Mindus-Amitiel-Debsin** [karashiiro/PingPlugin#33]
I am curious if your plugin is dependent on Windoze or the command prompt to make itself work.

I installed FFXIV several weeks ago from the Lutris FFXIV + Laucher option and almost everything has been working perfectly, aside from this.
![ffxiv_01112022_042419_369](https://user-images.githubusercontent.com/8101416/148942039-3bdf0bbb-6665-4c94-897a-2a6370e064c1.png)

So the game and its engine should be running on Lutris WINE, if that means anywhat to you!
I wish the best luck for your project, and would you please let I know if there is anything I can do to assist you in getting this working?
Thanks!

**Comment by karashiiro** [comment]
I was pretty sure I had resolved this in #27 - are you saying that the plugin has never worked for you, ever?

There are two ping trackers in the plugin that are supposed to work with WINE.

**Comment by Mindus-Amitiel-Debsin** [comment]
I have only been playing with Dalamud for a few weeks, and I have only been using your PingPlugin for a week or so. The ping has never worked, despite tweaking the options.
I am using version 1.15.1.0, though I don't know if this is a testing version or not. I just turned off testing versions and restarted and it is still the same version as before.
Unlike your #27 , I don't have nearly a great understanding of the underlying problems that might be causing this, but I would be willing to do whatever you require to troubleshoot this.

Thanks!

**Comment by karashiiro** [comment]
I just released 1.15.2, does it still happen on that version?

**Comment by Mindus-Amitiel-Debsin** [comment]
It works!
This is really nice. I will be able to play with my settings and ping, now. Thanks so much.
![ffxiv_01112022_184001_937](https://user-images.githubusercontent.com/8101416/149054270-ea49cec7-c630-4548-9863-77b36468af55.png)
