### ISSUE TITLE
Ping suddenly showing as much higher after update

### ISSUE THREAD

**Issue by sauronshotdogs** [karashiiro/PingPlugin#34]
After update ping will now spike wildly. For the last 2 months, it has been between 12-15 without ever going over 15, it is now at 60 minimum, with spikes to 200. Looking at resource manager, it is sitting steadily at 13 without moving. 

I'm not sure which to believe, or if my internet just decided to have ping for the first time.

**Comment by Oglaf** [comment]
The opposite happened to me, it used to be consistent 200/215ms, which is the same as in performance monitor. Now it keeps changing between 130~200ms.

WinPerf:
![image](https://user-images.githubusercontent.com/31038423/149143926-3953f9ea-ca34-48d7-a64e-63e173bbc44b.png)

FFXIV:
![image](https://user-images.githubusercontent.com/31038423/149144044-3cc95a25-3727-42c3-b0c9-eb081de3c448.png)

**Comment by karashiiro** [comment]
Should be fixed with v1.15.3, it was some debug code that I forgot to revert.

**Comment by sauronshotdogs** [comment]
All is back to normal. Thanks!

I was going crazy because I couldn't find anything backing up those numbers. Have a great day!
