### ISSUE TITLE
Ping does Not work with the OCE DC

### ISSUE THREAD

**Issue by IriGitt** [karashiiro/PingPlugin#35]
Hi There, Ping does not detect ping for the OCE Datacentre. It does detect the IP just shows a latency of 0. Screen Shot attached. Not a big issue, Just thought I would point it out. Thanks for your hard work.

![image](https://user-images.githubusercontent.com/98436912/151086814-8347bede-7417-4e94-87aa-0b97938f6ffc.png)

**Comment by karashiiro** [comment]
Out of curiosity, are you using WINE or any gaming VPN?

**Comment by IriGitt** [comment]
Nope. Just Straight windows 11

**Comment by LoboBiZARro** [comment]
I also am encountering this issue. And I am using BattlePing, but it used to work fine with BattlePing until the OCE update. I just restarted the game w/o BattlePing and the plug-in does work.

Just wanted to add that little bit of information.

**Comment by IriGitt** [comment]
Does it work for you on the OCE server tho? It works for me on all the other DCs, Just not Materia

**Comment by IriGitt** [comment]
Actually not completely, It keeps going to 0 for a few seconds

**Comment by IriGitt** [comment]
I have been playing around with it this morning and it looks to be working perfect. Thank you for your hard work!
