### ISSUE TITLE
Cant install/update

### ISSUE THREAD

**Issue by Theletha** [karashiiro/PingPlugin#36]
Logged in now and it says it failed to update the plugin and it wont install again.

**Comment by karashiiro** [comment]
If you completely remove the plugin (don't need to remove config though), does it still fail to install?

**Comment by Theletha** [comment]
remove from dalamud? it already removed itself when it failed the update :( 
Where is the config located for it?

**Comment by karashiiro** [comment]
The plugin itself is in `%AppData%\XIVLauncher\installedPlugins`, and the config is in `%AppData%\XIVLauncher\pluginConfigs`. I don't think you need to remove the current config for it to work, but you can try that too.

**Comment by IriGitt** [comment]
I just went into Dalamud and hit install again and it worked fine for me

**Comment by Theletha** [comment]
Removed it from both %AppData%\XIVLauncher\installedPlugins   and   %AppData%\XIVLauncher\pluginConfigs

i manage to install it again. and once i started changing settings for it it crashed and now it wont install again again. says contact plugin author.

**Comment by karashiiro** [comment]
Do you have a dalamud.log file I can use to debug this thoroughly? It should be in `%AppData%\XIVLauncher`.

**Comment by Theletha** [comment]
That log file was 120MB lol doesn't seem dalamud have a good Log file cleanup. For now i removed it and redid the steps i did in the earlier post. It now got installed and didn't crash when editing settings. I also fixed the game freezing when exiting.  

I'll check back tomorrow to see if it is stable during the gameplay then.

**Comment by Theletha** [comment]
Seem so have been fixed after that damn 120MB log file haha
