### ISSUE TITLE
2.0.1.0 Stacktrace

### ISSUE THREAD

**Issue by Xorag** [karashiiro/PingPlugin#39]
Win 10/Steam Client/No VPN

2022-01-28 18:50:29.589 -05:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PingPlugin.PingTrackers.PingTracker.AddressUpdateLoop(CancellationToken token) in K:\arashiiro\PingTrackers\PingTracker.cs:line 68
   --- End of inner exception stack trace ---

**Comment by karashiiro** [comment]
I released v2.0.2, does that fix this?

**Comment by Xorag** [comment]
> I released v2.0.2, does that fix this?

I'll update tomorrow and gladly check, its 2am for me atm :)

Thanks!

**Comment by Xorag** [comment]
Haven't had the issue occur so far today in a few hours of playing, I've zoned into a few instances briefly as well. Thanks!
