### ISSUE TITLE
[Loading Bug] DTR doesn't start

### ISSUE THREAD

**Issue by Infiziert90** [karashiiro/PingPlugin#53]
This is an issue with the recent multithreading changes in dalamud.
Some parts of dalamud, like the DTR bar, have no guards against multiple plugins trying to register at the same time, with the end result being that one of the plugins not survives the register process. 

Triggers are a) fast maschine b) bad timing on load.
For me it happens every single game start, so that i'm forced to disable and enable PingPlugin after load.

My fix for betterplaytime was to catch the exception and try again, same as if the name is already used.

**Comment by karashiiro** [comment]
Closed with https://github.com/goatcorp/DalamudPluginsD17/pull/1534
