### ISSUE TITLE
Where to translate title name？

### ISSUE THREAD

**Issue by ShadyWhite** [karashiiro/PingPlugin#9]
I could not find where to translate window's title name，like these:
![QQ截图20200610122415](https://user-images.githubusercontent.com/44015352/84226935-b6566680-ab15-11ea-9728-87cb484bb6e7.png)
![QQ图片20200610122443](https://user-images.githubusercontent.com/44015352/84226941-b8b8c080-ab15-11ea-9753-135a602067bc.png)

**Comment by karashiiro** [comment]
You can pull again, I just added the rows for that in 2271ea8

**Comment by ShadyWhite** [comment]
> You can pull again, I just added the rows for that in [2271ea8](https://github.com/karashiiro/PingPlugin/commit/2271ea8ff4e6357f99eb1926db5d94fe1f7452d6)

Thanks,done.
